### ISSUE TITLE
Project infrastructure setup

### ISSUE THREAD

**Issue by zainfathoni** [SantriHub/app#10]
## Overview

Setup development tools to support our process in writing standardised and reliable code.

## Definition of Done

1. Use [pkode](https://zainf.dev/pkode) CLI in the NPM scripts
2. Follow the guidelines documented in  [pkode](https://zainf.dev/pkode#readme)
3. All the scripts are incorporated in our GitHub Actions CI/CD processes

## Current Tasks

- [ ] Implement `lint` script
- [ ] Implement `format` script
- [ ] Implement `typecheck` script
- [ ] Implement `test` script
- [ ] Setup Git pre-commit hooks using husky & lint-staged
- [ ] Incorporate commitlint into the Git pre-commit hooks

## References

Please refer to these projects as examples

- Using `pkode`: https://github.com/senar-ai/web
- Manual setup (husky & commitlint): https://github.com/zainfathoni/kelas.rumahberbagi.com
